version: "3.1"
services:
  backend:
    container_name: backend
    hostname: backend
    restart: unless-stopped
    image: happyhyep/assignment2_back
    ports:
      - "8000:8000"
    networks:
      - default
      - corn_net  

  frontend:
    container_name: frontend
    hostname: frontend
    restart: unless-stopped
    image: happyhyep/assignment2_front
    ports:
      - "80:3000"
    networks:
      - default
      - corn_net  


networks:
  corn_net:
    driver: bridge
