kind: Deployment
apiVersion: apps/v1
metadata:
  name: back
  labels:
    app: back
spec:
  replicas: 3
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: back
        image: happyhyep/assignment3_back
        ports:
        - containerPort: 8000
---
apiVersion: v1                               
kind: Service                                    
metadata:
  name: nodeport-back             
spec:
  type: NodePort                                       
  selector:
    app: back    
  ports:                                                
  - port: 8000
    targetPort: 8000
    protocol: TCP